# Generated by Django 5.2 on 2025-04-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0002_rename_created_at_moodentry_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='feeling',
            field=models.CharField(help_text='How are you feeling today?', max_length=255),
        ),
    ]
