# Generated by Django 5.2 on 2025-04-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
